package Exception;

public class TryDemo {
public static void main(String[] args) {
	try
	{
		System.out.println("hello");
	}
	catch(ArithmeticException e){}
	//catch(InterruptedException e){}
	catch(Exception e){}
}
}
